version: '3'
services:
  mediawiki:
    container_name: wiki
    image: mediawiki
    restart: always
    ports:
      - 80:80
    links:
      - database
    volumes:
      - $HOME/volumes/mediawiki/images:/var/www/html/images   # After initial setup, download LocalSettings.php to the same directory as this yaml 

  database:
    image: mariadb
    container_name: db
    restart: always
    ports:
        - 3306:3306
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
    volumes:
       - $HOME/volumes/mysql/data:/var/lib/mysql
